# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# This pipeline will be extended to the MicroBuild template
trigger:
- dev
schedules:
- cron: "0 2 15 * *"
  displayName: "Monthly Run"
  branches:
    include:
    - dev
  always: true
resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool: 1ES-Shared-Hosted-Pool_Windows-Server-2022
    pool:
      vmImage: 'ubuntu-latest'
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: job
        steps:
        - task: GoTool@0
          inputs:
            version: '1.13.5'
        - task: Go@0
          inputs:
            command: 'get'
            arguments: '-d'
            workingDirectory: '$(System.DefaultWorkingDirectory)/azuredevops'
        - task: Go@0
          inputs:
            command: 'build'
            workingDirectory: '$(System.DefaultWorkingDirectory)/azuredevops'
        - task: Go@0
          inputs:
            command: 'test'
            arguments: '-v'
            workingDirectory: '$(System.DefaultWorkingDirectory)/azuredevops'
